//RESUME
#include<stdio.h>
int main()
{
    printf("             _____________________________________________________________________________________\n");
    printf("            |                                                                                     |\n");
    printf("            |                                                                                     |\n");
    printf("            |                                                                                     |\n");
    printf("            |                                                   |                                 |\n");
    printf("            |                   Data Scientist                  |                                 |\n");
    printf("            |                                                   |    Gaurav Upadhyay              |\n");
    printf("            |                                                   |                                 |\n");
    printf("            |                                                   |    garvmts2022@gmail.com        |\n");
    printf("            |                                                   |                                 |\n");
    printf("            |                                                   |    6387882422                   |\n");
    printf("            |                                                   |    6389384574                   |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                   CAREER OBJECTIVE                                  |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                                                                     |\n");
    printf("            |   Work and learn that contribute best for the growth of the organization by         |\n");
    printf("            |   continue developing and sharing my skill ability.                                 |\n");
    printf("            |                                                                                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                      SKILLS                                         |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                                                                     |\n");
    printf("            |   HTML                        I know HTML besics as well as HTML latest             |\n");
    printf("            |                                                                                     |\n");
    printf("            |   C programming               I also know C programming Language                    |\n");
    printf("            |                                                                                     |\n");
    printf("            |   CSS                           Cascading Style Sheet                               |\n");
    printf("            |                                                                                     |\n");
    printf("            |   Data Structure Using C                                                            |\n");
    printf("            |                                                                                     |\n");
    printf("            |   DataBase                        MySQL                                             |\n");
    printf("            |                                                                                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                     PROJECT                                         |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                                                                     |\n");
    printf("            |  Project Name:  Blood Bank                                                          |\n");
    printf("            |                                                                                     |\n");
    printf("            |  Role: Creating web-pages              Team Size: 25     Project Duration: 1 Month  |\n");
    printf("            |                                                                                     |\n");
    printf("            |  In our projects, we provide online registration for Doner as well as user can      |\n");
    printf("            |  appointment with doctors and so many faculties.                                    |\n");
    printf("            |                                                                                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                    EDUCATION                                        |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |_____________________________________________________________________________________|\n");
    printf("            | Degree/Course |  Institute/   |  University/  | Percentage/   | year of Passing     |\n");
    printf("            |               |  College      |   Board       |    CGPA       |                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |               |               |               |               |                     |\n");
    printf("            |   Diploma in  |  Mahamaya IT  |   Board of    |               |                     |\n");
    printf("            |   Computer    |  Polytechnic, |   technical   |     78%%       |      Pursuing       |\n");
    printf("            |   Science &   |  Kzushinagar  |   education   |               |                     |\n");
    printf("            |   Engineering |               | Utterpradesh  |               |                     |\n");
    printf("            |_______________|_______________|_______________|_______________|_____________________|\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                    ACHIVEMENTS                                      |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                                                                     |\n");
    printf("            |  C Programming                          Great learning Academy                      |\n");
    printf("            |  Language                                                                           |\n");
    printf("            |                                                                                     |\n");
    printf("            |  Data Structure                         Great Learning Academy                      |\n");
    printf("            |                                                                                     |\n");
    printf("            |  jQuery                                 IIT Madras through GUVI                     |\n");
    printf("            |                                                                                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                    STRENGTHS                                        |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                                                                     |\n");
    printf("            |   Unity, Helpful, Hard Work, Honesty                                                |\n");
    printf("            |                                                                                     |\n");
    printf("            |                                                                                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                 AREAS OF INTERESTS                                  |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                                                                     |\n");
    printf("            |   Coding, Learning                                                                  |\n");
    printf("            |                                                                                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                    HOBBIES                                          |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                                                                     |\n");
    printf("            |   Inventions & Experiments                                                          |\n");
    printf("            |                                                                                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                PERSONAL DETAILS                                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                                                                     |\n");
    printf("            |   Address                 Leelapur kalan, Hanumanganj, Prayagraj 221505             |\n");
    printf("            |                           Prayagraj, Utterpradesh, 221505                           |\n");
    printf("            |                                                                                     |\n");
    printf("            |   Date of Birth           05/06/2003                                                |\n");
    printf("            |                                                                                     |\n");
    printf("            |   Gender                  Male                                                      |\n");
    printf("            |                                                                                     |\n");
    printf("            |   Nationality             Indian                                                    |\n");
    printf("            |                                                                                     |\n");
    printf("            |   Marital Status          Commited                                                  |\n");
    printf("            |                                                                                     |\n");
    printf("            |   Languages Known         Hindi, English, Sanskrit, Gujarati                        |\n");
    printf("            |                                                                                     |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                  DECLARATION                                        |\n");
    printf("            |-------------------------------------------------------------------------------------|\n");
    printf("            |                                                                                     |\n");
    printf("            |   I hereby declare that all the details furnished here are true to the best of my   |\n");
    printf("            |   knowledge and belief.                                                             |\n");
    printf("            |                                                                                     |\n");
    printf("            |                                                                                     |\n");
    printf("            |                                                                                     |\n");
    printf("            |                                                                    Gaurav Upadhyay  |\n");
    printf("            |                                                                                     |\n");
    printf("            =======================================================================================\n");

getch();
}
